name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: |
        pnpm config set store-dir ~/.pnpm-store
        pnpm install --frozen-lockfile

    - name: Run tests
      run: pnpm test

    - name: Build application
      run: pnpm build

  # docker:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       context: .
  #       push: true
  #       tags: |
  #         ${{ secrets.DOCKERHUB_USERNAME }}/scraper-app:latest
  #         ${{ secrets.DOCKERHUB_USERNAME }}/scraper-app:${{ github.sha }}
  #       cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/scraper-app:buildcache
  #       cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/scraper-app:buildcache,mode=max